version: '3.8'

services:
  bankme-api:
    build:
      context: ./bankme-api
      dockerfile: Dockerfile
    container_name: bankme-api
    env_file:
      - path: ./bankme-api/.env
    ports:
      - '3000:3000'
